---
layout: docs
title: Aliases
index: 8
---

Aliases
=======
Ståle W. Pedersen
:Author:   Ståle W. Pedersen
:Email:    <spederse@redhat.com>
:source-highlighter: prettify

== Aliases

Aesh provide alias functionality similar to Bash alias. 

For those that do not know what aliases is, it allows a string to be substituted for a word when it is used as the first word of a simple command. Aesh maintains  a  list  of aliases  that  may  be set and unset with the +alias+ and +unalias+ commands.

Aesh always read a complete line of input before executing. Aliases are expanded when a command is read.

=== Set/Unset Aliases

Aliases are created with the +alias+ command either in the shell or specified in a file thats read when aesh starts. This file can be set in the +Settings+ class. The format to define aliases is: +alias aliasname='command -params'+. This is identical in a shell and file.

To remove an existing alias specify the name of the alias after the +unalias+ command. eg: +unalias aliasname+.

=== Alias persistence

By default aliases are enabled and must be turned off via the +Settings+ object. It will also try to read aliases from a the specified file and write to the file during shutdown. This can also be disabled if wanted.
